-- PlantMoji · Milestone 9 — raw sensor ingestion from the new Node-RED flow.
-- Additive and re-runnable. Apply before using POST /api/sensor-readings.

create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  reading_id text,
  plant_id text references public.plants (id),
  temperature numeric,
  humidity numeric,
  soil_ph numeric,
  light smallint,
  recorded_at timestamptz not null default now()
);

alter table public.sensor_readings add column if not exists reading_id text;
alter table public.sensor_readings add column if not exists plant_id text;
alter table public.sensor_readings add column if not exists temperature numeric;
alter table public.sensor_readings add column if not exists humidity numeric;
alter table public.sensor_readings add column if not exists soil_ph numeric;
alter table public.sensor_readings add column if not exists light smallint;
alter table public.sensor_readings add column if not exists recorded_at timestamptz default now();

create unique index if not exists sensor_readings_reading_id_uidx
  on public.sensor_readings (reading_id);

create index if not exists sensor_readings_plant_recorded_idx
  on public.sensor_readings (plant_id, recorded_at desc);

alter table public.sensor_readings enable row level security;
drop policy if exists "public read sensor_readings" on public.sensor_readings;
create policy "public read sensor_readings"
  on public.sensor_readings for select using (true);
