import { STREAK_TIMEZONE } from "@/types/game";
import type { AppLocale } from "@/lib/i18n";

export const QUIZ_CATEGORIES = ["temperature", "humidity", "light", "soil_ph", "crop", "safety", "plantmoji"] as const;
export type QuizCategory = (typeof QUIZ_CATEGORIES)[number];
type Localized = { en: string; id: string };
type QuizFact = { key:string; category:QuizCategory; question:Localized; choices:[Localized,Localized,Localized]; correct:number; explanation:Localized };
export type DailyQuizQuestion = { key:string; category:QuizCategory; question:string; choices:string[]; explanation?:string };
const L=(en:string,id:string):Localized=>({en,id});
const HINTS:Record<QuizCategory,Localized>={
  temperature:L("Hint: think about plant water loss and changing just one environmental factor.","Petunjuk: pikirkan kehilangan air pada tanaman dan ubah hanya satu faktor lingkungan."),
  humidity:L("Hint: separate moisture in the air from water stored in soil.","Petunjuk: bedakan uap air di udara dengan air yang tersimpan di tanah."),
  light:L("Hint: think about photosynthesis and what a simple light/dark sensor can observe.","Petunjuk: pikirkan fotosintesis dan apa yang dapat diamati sensor terang/gelap sederhana."),
  soil_ph:L("Hint: pH affects nutrients; measure carefully before changing soil.","Petunjuk: pH memengaruhi unsur hara; ukur dengan teliti sebelum mengubah tanah."),
  crop:L("Hint: use the crop's reference profile and Jember context, not a harvest guarantee.","Petunjuk: gunakan profil acuan tanaman dan konteks Jember, bukan jaminan panen."),
  safety:L("Hint: choose one reversible action that can be measured again.","Petunjuk: pilih satu tindakan yang dapat dibatalkan dan diukur kembali."),
  plantmoji:L("Hint: measured environmental compatibility is not the same as predicted yield.","Petunjuk: kecocokan lingkungan terukur tidak sama dengan prediksi hasil panen."),
};
export function quizHint(category:QuizCategory,locale:AppLocale){return HINTS[category][locale];}
const CASES=[
  {title:L("The Wilted-Leaf Mystery","Misteri Daun Layu"),intro:L("Read the environment, find the cause, and choose one safe test.","Baca lingkungan, temukan penyebab, lalu pilih satu percobaan yang aman.")},
  {title:L("Jember Crop Detective","Detektif Tanaman Jember"),intro:L("Use local crop knowledge and measured clues to solve today's field case.","Gunakan pengetahuan tanaman lokal dan petunjuk terukur untuk memecahkan kasus hari ini.")},
  {title:L("The Greenhouse Clue Trail","Jejak Petunjuk Rumah Kaca"),intro:L("Follow the clues from leaves, air, light, and soil—one observation at a time.","Ikuti petunjuk dari daun, udara, cahaya, dan tanah—satu pengamatan setiap langkah.")},
  {title:L("Jamkachu's Field Lab","Laboratorium Ladang Jamkachu"),intro:L("Build an explanation, test it gently, then check what the evidence says.","Susun penjelasan, uji dengan perlahan, lalu periksa buktinya.")},
  {title:L("The Crop Profile Challenge","Tantangan Profil Tanaman"),intro:L("Compare crop needs with real measurements without making a yield promise.","Bandingkan kebutuhan tanaman dengan pengukuran nyata tanpa menjanjikan hasil panen.")},
] as const;
export function farmCase(plantId:string,seed:string,locale:AppLocale,round=0){const item=CASES[hash(`${plantId}:${seed}:case:${round}`)%CASES.length];return{title:item.title[locale],intro:item.intro[locale],phases:locale==="id"?["AMATI","PAHAMI","BERTINDAK"]:["OBSERVE","UNDERSTAND","ACT"]};}

/** Reviewed agricultural learning bank. Numeric crop ranges mirror the
 * repository's approved Crop Profiles; general concepts follow FAO/USDA
 * education references. Three deterministic choice rotations create 60
 * question forms without changing scientific truth. */
const FACTS: QuizFact[] = [
  {key:"photosynthesis",category:"light",question:L("Why do green plants need light?","Mengapa tanaman hijau membutuhkan cahaya?"),choices:[L("To make sugars through photosynthesis","Untuk membuat gula melalui fotosintesis"),L("To raise soil pH","Untuk menaikkan pH tanah"),L("To measure air humidity","Untuk mengukur kelembapan udara")],correct:0,explanation:L("Photosynthesis uses light energy to turn water and carbon dioxide into sugars for growth.","Fotosintesis memakai energi cahaya untuk mengubah air dan karbon dioksida menjadi gula untuk pertumbuhan.")},
  {key:"low-light-sign",category:"light",question:L("A plant receives too little light for a long time. What may happen?","Tanaman kekurangan cahaya dalam waktu lama. Apa yang mungkin terjadi?"),choices:[L("Growth becomes weak or stretched","Pertumbuhan menjadi lemah atau memanjang"),L("Soil instantly becomes alkaline","Tanah langsung menjadi basa"),L("Roots stop needing air","Akar tidak lagi membutuhkan udara")],correct:0,explanation:L("Without enough light, plants make less energy and may grow pale, weak, or stretched.","Tanpa cukup cahaya, tanaman menghasilkan lebih sedikit energi dan dapat tumbuh pucat, lemah, atau memanjang.")},
  {key:"ldr-limit",category:"light",question:L("PlantMoji's binary light sensor is best at telling us…","Sensor cahaya biner PlantMoji paling baik untuk memberi tahu…"),choices:[L("Whether it is light or dark","Apakah kondisi terang atau gelap"),L("The exact photosynthesis rate","Laju fotosintesis yang tepat"),L("The amount of nitrogen in soil","Jumlah nitrogen dalam tanah")],correct:0,explanation:L("A binary LDR reports light/dark. It cannot measure the plant's exact photosynthesis rate.","LDR biner melaporkan terang/gelap. Sensor ini tidak mengukur laju fotosintesis tanaman secara tepat.")},
  {key:"transpiration",category:"temperature",question:L("What is transpiration?","Apa itu transpirasi?"),choices:[L("Water vapor leaving plant leaves","Uap air keluar dari daun tanaman"),L("Roots producing sunlight","Akar menghasilkan cahaya matahari"),L("Soil changing into fertilizer","Tanah berubah menjadi pupuk")],correct:0,explanation:L("Plants lose water vapor mainly through tiny leaf openings called stomata.","Tanaman kehilangan uap air terutama melalui lubang kecil pada daun yang disebut stomata.")},
  {key:"heat-water-loss",category:"temperature",question:L("Why can hot conditions increase plant water stress?","Mengapa kondisi panas dapat meningkatkan stres air pada tanaman?"),choices:[L("Water can evaporate and leave the plant faster","Air dapat menguap dan keluar dari tanaman lebih cepat"),L("Heat creates extra soil","Panas menciptakan tanah tambahan"),L("Hot air always contains fertilizer","Udara panas selalu mengandung pupuk")],correct:0,explanation:L("Heat can increase evaporation and transpiration, so observation and water management become important.","Panas dapat meningkatkan penguapan dan transpirasi, sehingga pengamatan dan pengelolaan air menjadi penting.")},
  {key:"heat-experiment",category:"temperature",question:L("A potted crop is above its temperature reference. Which experiment is most useful?","Tanaman pot berada di atas acuan suhu. Percobaan mana paling berguna?"),choices:[L("Move it to safe shade and measure again","Pindahkan ke tempat teduh yang aman lalu ukur lagi"),L("Change several conditions at once","Ubah banyak kondisi sekaligus"),L("Ignore the next sensor reading","Abaikan pembacaan sensor berikutnya")],correct:0,explanation:L("Changing one factor and measuring again makes cause and effect easier to understand.","Mengubah satu faktor lalu mengukur lagi membuat hubungan sebab-akibat lebih mudah dipahami.")},
  {key:"humidity-meaning",category:"humidity",question:L("Air humidity describes…","Kelembapan udara menggambarkan…"),choices:[L("Water vapor in the air","Uap air di udara"),L("Water stored in soil","Air yang tersimpan di tanah"),L("Acidity of soil","Keasaman tanah")],correct:0,explanation:L("Relative humidity describes moisture in the air. It is not a soil-moisture reading.","Kelembapan relatif menggambarkan uap air di udara, bukan kelembapan tanah.")},
  {key:"humidity-transpiration",category:"humidity",question:L("When air is very dry, water vapor usually leaves leaves…","Saat udara sangat kering, uap air biasanya keluar dari daun…"),choices:[L("More readily","Lebih mudah"),L("Not at all","Tidak sama sekali"),L("Only through roots","Hanya melalui akar")],correct:0,explanation:L("A larger moisture difference between leaf and dry air can increase water loss through transpiration.","Perbedaan kelembapan yang lebih besar antara daun dan udara kering dapat meningkatkan kehilangan air melalui transpirasi.")},
  {key:"humidity-observation",category:"humidity",question:L("The air-humidity reading is low near an AC vent. What should students test?","Kelembapan udara rendah dekat ventilasi AC. Apa yang perlu diuji siswa?"),choices:[L("Move the pot away from direct airflow and compare readings","Jauhkan pot dari aliran langsung lalu bandingkan pembacaan"),L("Add random material to the soil","Tambahkan bahan acak ke tanah"),L("Assume soil is dry without measuring it","Anggap tanah kering tanpa mengukurnya")],correct:0,explanation:L("A controlled location change tests whether direct dry airflow affects the measured environment.","Perubahan lokasi yang terkontrol menguji apakah aliran udara kering memengaruhi lingkungan terukur.")},
  {key:"roots-air",category:"crop",question:L("Why do most crop roots need air spaces in soil?","Mengapa akar sebagian besar tanaman membutuhkan rongga udara di tanah?"),choices:[L("Roots need oxygen for respiration","Akar membutuhkan oksigen untuk respirasi"),L("Roots perform photosynthesis in darkness","Akar berfotosintesis dalam gelap"),L("Air spaces automatically raise pH","Rongga udara otomatis menaikkan pH")],correct:0,explanation:L("Waterlogged soil can lose air spaces, making root respiration difficult; drainage helps remove excess water.","Tanah tergenang dapat kehilangan rongga udara dan menyulitkan respirasi akar; drainase membantu membuang kelebihan air.")},
  {key:"ph-nutrients",category:"soil_ph",question:L("Why is soil pH important to crops?","Mengapa pH tanah penting bagi tanaman?"),choices:[L("It affects nutrient availability and soil organisms","pH memengaruhi ketersediaan unsur hara dan organisme tanah"),L("It measures sunlight","pH mengukur cahaya matahari"),L("It gives the exact harvest date","pH memberi tanggal panen yang tepat")],correct:0,explanation:L("Soil pH changes mineral solubility and biological activity, affecting which nutrients roots can access.","pH tanah mengubah kelarutan mineral dan aktivitas biologis, sehingga memengaruhi unsur hara yang dapat diserap akar.")},
  {key:"ph-scale",category:"soil_ph",question:L("Compared with pH 7, soil at pH 6 is…","Dibandingkan pH 7, tanah dengan pH 6…"),choices:[L("Ten times more acidic on the pH scale","Sepuluh kali lebih asam pada skala pH"),L("One percent more humid","Satu persen lebih lembap"),L("Twice as bright","Dua kali lebih terang")],correct:0,explanation:L("The pH scale is logarithmic: a change of one pH unit represents a tenfold change in acidity.","Skala pH bersifat logaritmik: perubahan satu unit pH berarti perubahan keasaman sepuluh kali lipat.")},
  {key:"ph-sampling",category:"soil_ph",question:L("A soil pH result looks unusual. What is the best next step?","Hasil pH tanah terlihat tidak biasa. Apa langkah berikutnya?"),choices:[L("Repeat a careful measurement and ask a teacher before treatment","Ulangi pengukuran dengan teliti dan minta bantuan guru sebelum perawatan"),L("Immediately add an unknown chemical","Segera tambahkan bahan kimia yang tidak dikenal"),L("Use the air-humidity value as pH","Gunakan nilai kelembapan udara sebagai pH")],correct:0,explanation:L("Confirm the observation first. Soil amendments require crop-specific, qualified guidance.","Pastikan pengamatan terlebih dahulu. Pembenah tanah memerlukan panduan yang sesuai tanaman dan dari orang berpengetahuan.")},
  {key:"strawberry-temp",category:"crop",question:L("PlantMoji's strawberry profile recommends which temperature range?","Profil stroberi PlantMoji merekomendasikan rentang suhu mana?"),choices:[L("20–24°C","20–24°C"),L("5–10°C","5–10°C"),L("35–40°C","35–40°C")],correct:0,explanation:L("The current classroom strawberry profile uses 20–24°C as its recommended reference; varieties may differ.","Profil stroberi kelas saat ini memakai 20–24°C sebagai acuan rekomendasi; varietas dapat berbeda.")},
  {key:"strawberry-ph",category:"crop",question:L("What soil-pH reference is stored for strawberry in PlantMoji?","Acuan pH tanah apa yang tersimpan untuk stroberi di PlantMoji?"),choices:[L("5.5–6.5","5,5–6,5"),L("2.0–3.0","2,0–3,0"),L("9.0–10.0","9,0–10,0")],correct:0,explanation:L("The stored strawberry reference is pH 5.5–6.5 and is guidance, not a chemical-treatment instruction.","Acuan stroberi yang tersimpan adalah pH 5,5–6,5 dan merupakan panduan, bukan instruksi perlakuan kimia.")},
  {key:"pepper-humidity",category:"crop",question:L("Which air-humidity range is in PlantMoji's cayenne-pepper profile?","Rentang kelembapan udara mana yang ada di profil cabai rawit PlantMoji?"),choices:[L("60–80%","60–80%"),L("0–10%","0–10%"),L("95–100% only","Hanya 95–100%")],correct:0,explanation:L("The classroom cayenne-pepper profile uses 60–80% relative humidity as its reference.","Profil cabai rawit kelas memakai kelembapan relatif 60–80% sebagai acuannya.")},
  {key:"soybean-jember",category:"crop",question:L("Why is soybean included in the Jember Crop Explorer?","Mengapa kedelai termasuk dalam Jember Crop Explorer?"),choices:[L("Jember is one of East Java's soybean production centers","Jember merupakan salah satu sentra kedelai di Jawa Timur"),L("Soybean is a type of soil sensor","Kedelai adalah jenis sensor tanah"),L("Soybean grows without light","Kedelai tumbuh tanpa cahaya")],correct:0,explanation:L("Indonesia's agricultural standards agency identifies Jember as a soybean center in East Java.","Badan standardisasi pertanian Indonesia menyebut Jember sebagai salah satu sentra kedelai di Jawa Timur.")},
  {key:"jember-research",category:"crop",question:L("Which crops are connected to seed research visits at Puslitkoka in Jember?","Tanaman apa yang terkait dengan kunjungan riset benih di Puslitkoka Jember?"),choices:[L("Coffee and cocoa","Kopi dan kakao"),L("Wheat and tulips","Gandum dan tulip"),L("Cactus and pine","Kaktus dan pinus")],correct:0,explanation:L("Indonesian agricultural researchers studied coffee and cocoa seed preparation at Puslitkoka in Jember.","Peneliti pertanian Indonesia mempelajari persiapan benih kopi dan kakao di Puslitkoka, Jember.")},
  {key:"profile-meaning",category:"plantmoji",question:L("What does “3 of 4 measured conditions matched” tell a farmer?","Apa arti “3 dari 4 kondisi terukur cocok” bagi petani?"),choices:[L("Three measured values fit that profile's reference ranges","Tiga nilai terukur sesuai rentang acuan profil"),L("Harvest is guaranteed at 75%","Panen dijamin 75%"),L("No field observation is needed","Pengamatan lapangan tidak diperlukan")],correct:0,explanation:L("Environmental matching is a transparent comparison of measured dimensions, not a yield prediction.","Kecocokan lingkungan adalah perbandingan transparan dari dimensi terukur, bukan prediksi hasil panen.")},
  {key:"field-method",category:"safety",question:L("Which method produces the clearest farming experiment?","Metode mana yang menghasilkan percobaan pertanian paling jelas?"),choices:[L("Change one factor, record it, and measure again","Ubah satu faktor, catat, lalu ukur lagi"),L("Change everything and rely on memory","Ubah semuanya dan mengandalkan ingatan"),L("Keep only results you like","Simpan hanya hasil yang disukai")],correct:0,explanation:L("Changing one factor and keeping notes makes observations easier to compare and repeat.","Mengubah satu faktor dan membuat catatan memudahkan pengamatan untuk dibandingkan dan diulang.")},
];

function hash(value:string):number{let h=2166136261;for(let i=0;i<value.length;i++)h=Math.imul(h^value.charCodeAt(i),16777619);return h>>>0;}
export function wibDate(now=new Date()):string{return new Intl.DateTimeFormat("en-CA",{timeZone:STREAK_TIMEZONE,year:"numeric",month:"2-digit",day:"2-digit"}).format(now);}
function variantFact(fact:QuizFact,variant:number,locale:AppLocale):DailyQuizQuestion&{correctIndex:number}{const shift=variant%3;const choices=[0,1,2].map(i=>fact.choices[(i+shift)%3][locale]);return{key:`${fact.key}-v${variant+1}`,category:fact.category,question:fact.question[locale],choices,correctIndex:(fact.correct-shift+3)%3,explanation:fact.explanation[locale]};}
export function quizByKey(key:string,locale:AppLocale){const m=/^(.*)-v([1-3])$/.exec(key);if(!m)return null;const fact=FACTS.find(f=>f.key===m[1]);return fact?variantFact(fact,Number(m[2])-1,locale):null;}
export function dailyQuiz(plantId:string,locale:AppLocale,date=wibDate()):Array<DailyQuizQuestion&{correctIndex:number}>{const pool=FACTS.map(f=>variantFact(f,hash(`${plantId}:${date}:${f.key}`)%3,locale)).sort((a,b)=>hash(`${plantId}:${date}:${a.key}`)-hash(`${plantId}:${date}:${b.key}`));const picked:typeof pool=[];const seen=new Set<QuizCategory>();for(const q of pool){if(!seen.has(q.category)){picked.push(q);seen.add(q.category);}if(picked.length===3)break;}return picked;}
export const QUIZ_QUESTION_COUNT=FACTS.length*3;
