import { STREAK_TIMEZONE } from "@/types/game";
import type { AppLocale } from "@/lib/i18n";

export const QUIZ_CATEGORIES = ["temperature", "humidity", "light", "soil_ph", "crop", "safety", "plantmoji"] as const;
export type QuizCategory = (typeof QUIZ_CATEGORIES)[number];
type Localized = { en: string; id: string };
type QuizFact = { key: string; category: QuizCategory; question: Localized; choices: [Localized, Localized, Localized]; correct: number; explanation: Localized };
export type DailyQuizQuestion = { key: string; category: QuizCategory; question: string; choices: string[]; explanation?: string };

const L = (en: string, id: string): Localized => ({ en, id });
const FACTS: QuizFact[] = [
  { key:"hot-action",category:"temperature",question:L("A plant is hotter than its reference range. What is the safest first step?","Tanaman lebih panas dari rentang acuannya. Apa langkah awal paling aman?"),choices:[L("Move it to a cooler, shaded place","Pindahkan ke tempat lebih sejuk dan teduh"),L("Cover the sensor","Tutupi sensor"),L("Add an unknown chemical","Tambahkan bahan kimia yang tidak dikenal")],correct:0,explanation:L("A cooler, shaded location is reversible. Measure again to see whether it helped.","Tempat yang sejuk dan teduh mudah dicoba. Ukur lagi untuk melihat hasilnya.")},
  { key:"temp-truth",category:"temperature",question:L("Who decides whether temperature matches a crop range?","Siapa yang menentukan apakah suhu cocok dengan rentang tanaman?"),choices:[L("The measured value and crop profile","Nilai sensor dan profil tanaman"),L("Jamkachu's guess","Tebakan Jamkachu"),L("The loudest answer","Jawaban paling keras")],correct:0,explanation:L("PlantMoji compares real measurements with a stored reference range.","PlantMoji membandingkan pengukuran nyata dengan rentang acuan tersimpan.")},
  { key:"remeasure-temp",category:"temperature",question:L("After moving a hot plant, what should you do next?","Setelah memindahkan tanaman yang panas, apa berikutnya?"),choices:[L("Measure again","Ukur lagi"),L("Claim it is fixed immediately","Langsung anggap sudah pulih"),L("Turn off every sensor","Matikan semua sensor")],correct:0,explanation:L("A second measurement verifies whether the environment really changed.","Pengukuran kedua memastikan apakah lingkungan benar-benar berubah.")},
  { key:"air-not-soil",category:"humidity",question:L("The humidity sensor in PlantMoji measures…","Sensor kelembapan di PlantMoji mengukur…"),choices:[L("Water vapor in the air","Uap air di udara"),L("Water inside the soil","Air di dalam tanah"),L("The plant's age","Umur tanaman")],correct:0,explanation:L("Air humidity and soil moisture are different measurements.","Kelembapan udara dan kelembapan tanah adalah pengukuran berbeda.")},
  { key:"dry-air",category:"humidity",question:L("The air is too dry. Which observation is useful?","Udara terlalu kering. Pengamatan mana yang berguna?"),choices:[L("Check whether a fan or AC blows nearby","Periksa kipas atau AC di dekatnya"),L("Guess the soil pH","Tebak pH tanah"),L("Hide the reading","Sembunyikan hasil sensor")],correct:0,explanation:L("Moving away from direct fan or AC airflow is a low-risk test.","Menjauh dari aliran kipas atau AC adalah percobaan berisiko rendah.")},
  { key:"humidity-unit",category:"humidity",question:L("Air humidity is commonly shown as…","Kelembapan udara biasanya ditampilkan sebagai…"),choices:[L("A percentage","Persentase"),L("A color only","Hanya warna"),L("Plant age in days","Umur tanaman dalam hari")],correct:0,explanation:L("Relative humidity is displayed as a percentage.","Kelembapan relatif ditampilkan sebagai persentase.")},
  { key:"low-light",category:"light",question:L("Light is below the crop reference. What is a sensible test?","Cahaya di bawah acuan tanaman. Apa percobaan yang masuk akal?"),choices:[L("Move toward safe natural light","Pindahkan menuju cahaya alami yang aman"),L("Add soil chemicals","Tambahkan bahan kimia tanah"),L("Change the reading by hand","Ubah angka sensor secara manual")],correct:0,explanation:L("Change light exposure gently, then observe the sensor again.","Ubah paparan cahaya perlahan, lalu amati sensor lagi.")},
  { key:"light-verify",category:"light",question:L("How does PlantMoji verify a light-care action?","Bagaimana PlantMoji memverifikasi tindakan terkait cahaya?"),choices:[L("With later sensor readings","Dengan pembacaan sensor berikutnya"),L("By counting button taps","Dengan menghitung ketukan tombol"),L("By asking AI to guess","Dengan meminta AI menebak")],correct:0,explanation:L("The next real sensor readings confirm whether light improved.","Pembacaan sensor nyata berikutnya memastikan apakah cahaya membaik.")},
  { key:"light-safe",category:"light",question:L("Which light action is easiest to reverse?","Tindakan cahaya mana yang paling mudah dibatalkan?"),choices:[L("Move the pot a little and observe","Geser pot sedikit lalu amati"),L("Replace the plant","Ganti tanamannya"),L("Ignore every measurement","Abaikan semua pengukuran")],correct:0,explanation:L("Small position changes let students observe cause and effect safely.","Perubahan posisi kecil membantu siswa mengamati sebab dan akibat dengan aman.")},
  { key:"ph-help",category:"soil_ph",question:L("Soil pH looks wrong. What should a student do?","pH tanah terlihat tidak sesuai. Apa yang harus dilakukan siswa?"),choices:[L("Ask a teacher or farmer for help","Minta bantuan guru atau petani"),L("Add a random chemical","Tambahkan bahan kimia acak"),L("Taste the soil","Cicipi tanah")],correct:0,explanation:L("Soil treatment needs knowledgeable adult guidance; PlantMoji does not give chemical doses.","Perawatan tanah memerlukan panduan orang dewasa; PlantMoji tidak memberi dosis bahan kimia.")},
  { key:"ph-seven",category:"soil_ph",question:L("A soil pH of 7 is called…","pH tanah 7 disebut…"),choices:[L("Neutral","Netral"),L("Very hot","Sangat panas"),L("Very bright","Sangat terang")],correct:0,explanation:L("On the pH scale, 7 is neutral.","Pada skala pH, angka 7 bersifat netral.")},
  { key:"ph-not-mood",category:"soil_ph",question:L("Can tapping Jamkachu change real soil pH?","Apakah mengetuk Jamkachu dapat mengubah pH tanah nyata?"),choices:[L("No","Tidak"),L("Yes, instantly","Ya, seketika"),L("Only at night","Hanya malam hari")],correct:0,explanation:L("Interactions are playful feedback; real conditions require real-world action and measurement.","Interaksi memberi umpan balik bermain; kondisi nyata memerlukan tindakan dan pengukuran nyata.")},
  { key:"profile-purpose",category:"crop",question:L("What does a crop profile contain?","Apa isi profil tanaman?"),choices:[L("Reference environmental ranges","Rentang lingkungan acuan"),L("A guaranteed harvest date","Tanggal panen yang dijamin"),L("A magic growth score","Skor pertumbuhan ajaib")],correct:0,explanation:L("Profiles provide reference ranges, not a guarantee of yield or success.","Profil menyediakan rentang acuan, bukan jaminan hasil panen.")},
  { key:"match-meaning",category:"crop",question:L("“3 of 4 matched” means…","“3 dari 4 cocok” berarti…"),choices:[L("Three measured conditions fit their references","Tiga kondisi terukur sesuai acuannya"),L("A 75% harvest guarantee","Jaminan panen 75%"),L("The crop will grow automatically","Tanaman akan tumbuh otomatis")],correct:0,explanation:L("Environmental match describes only the measured dimensions.","Kecocokan lingkungan hanya menjelaskan dimensi yang diukur.")},
  { key:"missing-data",category:"crop",question:L("If one sensor value is missing, PlantMoji should…","Jika satu nilai sensor hilang, PlantMoji harus…"),choices:[L("Mark it not evaluated","Tandai belum dievaluasi"),L("Call it a mismatch","Sebut tidak cocok"),L("Invent a value","Mengarang nilai")],correct:0,explanation:L("Unavailable data is not evidence of a mismatch.","Data yang tidak tersedia bukan bukti ketidakcocokan.")},
  { key:"no-dose",category:"safety",question:L("Which recommendation should PlantMoji avoid?","Rekomendasi mana yang harus dihindari PlantMoji?"),choices:[L("Unverified chemical dosage","Dosis bahan kimia yang belum terverifikasi"),L("Observe and measure again","Amati dan ukur lagi"),L("Ask a teacher for help","Minta bantuan guru")],correct:0,explanation:L("PlantMoji favors reversible actions and qualified help for soil intervention.","PlantMoji mengutamakan tindakan yang dapat dibatalkan dan bantuan ahli untuk tanah.")},
  { key:"sensor-cover",category:"safety",question:L("Why shouldn't you cover a sensor to improve its number?","Mengapa sensor tidak boleh ditutupi agar angkanya terlihat lebih baik?"),choices:[L("It hides reality instead of helping the plant","Itu menyembunyikan kenyataan, bukan membantu tanaman"),L("It gives bonus XP","Itu memberi bonus XP"),L("It changes the crop profile","Itu mengubah profil tanaman")],correct:0,explanation:L("Good experiments change the environment, not the evidence.","Percobaan yang baik mengubah lingkungan, bukan buktinya.")},
  { key:"safe-cycle",category:"safety",question:L("Which learning cycle is safest?","Siklus belajar mana yang paling aman?"),choices:[L("Observe, act gently, measure again","Amati, bertindak perlahan, ukur lagi"),L("Guess, dose, ignore","Tebak, beri dosis, abaikan"),L("Tap, claim, stop","Ketuk, nyatakan berhasil, berhenti")],correct:0,explanation:L("Small reversible actions make cause and effect easier to learn.","Tindakan kecil yang dapat dibatalkan memudahkan belajar sebab dan akibat.")},
  { key:"growth-stage",category:"plantmoji",question:L("Who changes the real plant's Growth Stage?","Siapa yang mengubah Growth Stage tanaman nyata?"),choices:[L("The student through a Growth Note","Siswa melalui Growth Note"),L("The humidity sensor automatically","Sensor kelembapan secara otomatis"),L("Gemini","Gemini")],correct:0,explanation:L("Real Growth Stage stays a manual observation in the growth diary.","Growth Stage nyata tetap merupakan pengamatan manual di catatan pertumbuhan.")},
  { key:"xp-truth",category:"plantmoji",question:L("Does repeatedly tapping a care button earn quest XP?","Apakah mengetuk tombol perawatan berulang kali memberi XP misi?"),choices:[L("No, sensors must verify real improvement","Tidak, sensor harus memverifikasi perbaikan nyata"),L("Yes, every tap earns XP","Ya, setiap ketukan memberi XP"),L("Only if AI approves","Hanya jika AI menyetujui")],correct:0,explanation:L("Buttons give feedback; verified care completes quests and earns their XP.","Tombol memberi respons; perawatan terverifikasi menyelesaikan misi dan memberi XP.")},
];

function hash(value: string): number { let h = 2166136261; for (let i=0;i<value.length;i++) h = Math.imul(h ^ value.charCodeAt(i), 16777619); return h >>> 0; }
export function wibDate(now = new Date()): string { return new Intl.DateTimeFormat("en-CA", { timeZone: STREAK_TIMEZONE, year:"numeric", month:"2-digit", day:"2-digit" }).format(now); }
function variantFact(fact: QuizFact, variant: number, locale: AppLocale): DailyQuizQuestion & { correctIndex: number } {
  const shift = variant % 3;
  const choices = [0,1,2].map((i) => fact.choices[(i + shift) % 3][locale]);
  return { key:`${fact.key}-v${variant+1}`, category:fact.category, question:fact.question[locale], choices, correctIndex:(fact.correct-shift+3)%3, explanation:fact.explanation[locale] };
}
export function quizByKey(key: string, locale: AppLocale) { const m=/^(.*)-v([1-3])$/.exec(key); if(!m) return null; const fact=FACTS.find(f=>f.key===m[1]); return fact ? variantFact(fact,Number(m[2])-1,locale) : null; }
export function dailyQuiz(plantId: string, locale: AppLocale, date = wibDate()): Array<DailyQuizQuestion & { correctIndex: number }> {
  const pool=FACTS.map((fact)=>variantFact(fact,hash(`${plantId}:${date}:${fact.key}`)%3,locale)).sort((a,b)=>hash(`${plantId}:${date}:${a.key}`)-hash(`${plantId}:${date}:${b.key}`));
  const picked: typeof pool=[]; const seen=new Set<QuizCategory>();
  for(const q of pool){ if(!seen.has(q.category)){picked.push(q);seen.add(q.category);} if(picked.length===3) break; }
  return picked;
}
export const QUIZ_QUESTION_COUNT = FACTS.length * 3;
